[[MemberLeaveAbsence-API]]
= MemberLeaveAbsence-API
회원 휴학 정보를 조회 및 관리할 수 있는 api 입니다.

[[MemberLeaveAbsence-Add-Single]]
== POST : /mms/api/v1/member-leave-absence
=== 단일 회원 휴학 정보를 등록
[cols="1,1"]
|===
|authorization
|true

|Role
|admin

|add user info
|false
|===

operation::member-leave-absence-add-single[snippets='request-fields,request-body,response-fields,response-body,http-request,http-response']

[[MemberLeaveAbsence-Get-Single]]
== GET : /mms/api/v1/member-leave-absence/{memberID}
=== 단일 회원 휴학 정보를 조회
=== Route Options
[cols="1,1"]
|===
|authorization
|true

|Role
|admin

|add user info
|false
|===

operation::member-leave-absence-get-single[snippets='path-parameters,response-fields,response-body,http-request,http-response,']

[[MemberLeaveAbsence-Get-Multiple]]
== GET : /mms/api/v1/member-leave-absence/
=== 다수 회원 휴학 정보를 조회
=== Route Options
[cols="1,1"]
|===
|authorization
|true

|Role
|admin

|add user info
|false
|===

Query Options, 혹은 Page Options 등을 사용하여 attendance를 조회하거나, pagination 작업을 수행할 수 있습니다.

*주의!* 모든 option들은 단 한개의 인자만 수용가능합니다!

* (O) "?memberID=456465456&timeTableID=1"
* (X) "?memberID=456465456,456456456465&timeTableID=1,123123"

또한 모든 Option들은 And로 동작합니다.

만약 "?memberID=456465456&timeTableID=1"라는 인자가 있다면, memberID가 "456465456"이고, timeTableID가 1인 Attendance를 찾습니다.


=== Equal Query Options
해당 옵션들은 입력된 값과 완전히 일치 되는 경우를 탐색합니다.
예를들어 "timeTableID = 1" 옵션을 제공하면, TimeTable(Object)의 ID가 1인 attendance들을 조회합니다.
[cols="10,10,10"]
|===
|param name|type|description

|status
|Bool
|해당 Member의 휴학 여부
|===

=== Range Query Options
해당 옵션들을 사용하여 범위를 검색할 수 있습니다.

예를들어, "createdDateTime" 옵션을 검색하고 싶다면,
"startCreatedDateTime"으로 시작 범위를 설정하고 "endCreatedDateTime"으로 종료 범위를 설정하여 검색할 수 있습니다.

* 시작 범위와 종료 범위가 모두 입력되었다면, 해당 범위를 탐색합니다.
* 시작 범위만 입력됬을 경우, 해당 시작범위에서 최대 범위(9999-12-31 59:59:59)에 해당하는 범위를 탐색합니다.
* 종료 범위만 입력됬을 경우, 최소 범위("1000-01-01 00:00:00")에서 종료 범위까지에 해당하는 범위를 탐색합니다.

[cols="10,10,10,10,10"]
|===
|name|type|start range param|end range param|description

|ExpectedDateOfReturnSchool
|Date(yyyy-MM-dd)
|startExpectedDateOfReturnSchool
|endExpectedDateOfReturnSchool
|해당 Member의 휴학 예정일
|===

=== Pagination Options
해당 인자를 통해 pagination처리를 할 수 있습니다. Sort Option은 아래 파트를 참고하세요.

*주의!* pagination을 설정하지 않더라도, 모든 request는 1000의 Size로 자동으로 pagination처리가 됩니다!
만약 1000건 보다 많은 양의 데이터가 필요하다면, size를 지정해주어야합니다.
[cols="10,10,10"]
|===
|param name|description

|size
|Page의 크기

|page
|Page의 위치
|===

=== Sort Options
Sort Option은 "sort" 인자에 제공해야합니다. 위 옵션들과 다르게 Sort Option은 여러 인자들을 입력해도 됩니다.

sort 인자에 모든 Option들을 지정했다면, 마지막 인자로 Sort 방향을 지정해주여야 합니다. ASC(오름차순), DESC(내림차순) 2가지 옵션이 있습니다.
만약 옵션을 지정해주지 않았다면, DESC로 동작합니다.

사용예시 "sort=member,asc", "sort=member,timeTable,desc"

*주의!* Sort Option을 지정해주지 않더라도, 기본적으로 Id에 대하여 DESC 방향으로 정렬을 진행합니다!
[cols="10,10"]
|===
|param name|description

|id
|memberLeaveAbsence의 id

|member
|member의 uid

|status
|member의 휴학 여부

|expectedDateOfReturnSchool
|member의 휴학 예정일
|===

operation::member-leave-absence-get-multiple[snippets='response-fields,response-body,http-request,http-response,']

[[MemberLeaveAbsence-Del-Single]]
== DELETE : /mms/api/v1/member-leave-absence/{memberID}
=== 단일 회원 휴학 정보를 삭제
=== Route Options
[cols="1,1"]
|===
|authorization
|true

|Role
|admin

|add user info
|false
|===

operation::member-leave-absence-del-single[snippets='path-parameters,response-fields,response-body,http-request,http-response']

[[MemberLeaveAbsence-Del-Bulk]]
== DELETE : /mms/api/v1/member-leave-absence/
=== 다수 회원 휴학 정보를 삭제
=== Route Options
[cols="1,1"]
|===
|authorization
|true

|Role
|admin

|add user info
|false
|===

operation::member-leave-absence-del-bulk[snippets='request-fields,request-body,response-fields,response-body,http-request,http-response,']

[[MemberLeaveAbsence-Update-Single]]
== PUT : /mms/api/v1/member-leave-absence/{memberID}
=== 단일 회원 휴학 정보를 업데이트
=== Route Options
[cols="1,1"]
|===
|authorization
|true

|Role
|admin

|add user info
|false
|===

operation::member-leave-absence-update-single[snippets='request-fields,request-body,response-fields,response-body,http-request,http-response,']